import type { NodeDefinition } from "./types.js";

export const INPUT_NODE_DEFS: NodeDefinition[] = [
  {
    name: "input_text",
    title: "Input: Text",
    category: "input",
    description: "Local text input node.",
    inputs: [],
    outputs: [{ id: "text", label: "Text Data", type: "text" }],
    params: [],
    defaults: {},
    outputMode: "text",
    wrapperAvailable: false,
    rawCliAvailable: false,
    constraints: {},
    warnings: [],
  },
  {
    name: "input_image",
    title: "Input: Image",
    category: "input",
    description: "Local image input node.",
    inputs: [],
    outputs: [{ id: "image", label: "Image Data", type: "image" }],
    params: [],
    defaults: {},
    outputMode: "image",
    wrapperAvailable: false,
    rawCliAvailable: false,
    constraints: {},
    warnings: [],
  },
  {
    name: "input_video",
    title: "Input: Video",
    category: "input",
    description: "Local video input node.",
    inputs: [],
    outputs: [{ id: "video", label: "Video Data", type: "video" }],
    params: [],
    defaults: {},
    outputMode: "video",
    wrapperAvailable: false,
    rawCliAvailable: false,
    constraints: {},
    warnings: [],
  },
  {
    name: "input_audio",
    title: "Input: Audio",
    category: "input",
    description: "Local audio input node.",
    inputs: [],
    outputs: [{ id: "audio", label: "Audio Data", type: "audio" }],
    params: [],
    defaults: {},
    outputMode: "audio",
    wrapperAvailable: false,
    rawCliAvailable: false,
    constraints: {},
    warnings: [],
  },
];

export const OUTPUT_NODE_DEFS: NodeDefinition[] = [
  {
    name: "output_image",
    title: "Display: Image",
    category: "output",
    description: "Image output display.",
    inputs: [{ id: "image", label: "Image Data", type: "image", required: true }],
    outputs: [],
    params: [],
    defaults: {},
    outputMode: "image",
    wrapperAvailable: false,
    rawCliAvailable: false,
    constraints: {},
    warnings: [],
  },
  {
    name: "output_video",
    title: "Display: Video",
    category: "output",
    description: "Video output display.",
    inputs: [{ id: "video", label: "Video Data", type: "video", required: true }],
    outputs: [],
    params: [],
    defaults: {},
    outputMode: "video",
    wrapperAvailable: false,
    rawCliAvailable: false,
    constraints: {},
    warnings: [],
  },
  {
    name: "output_text",
    title: "Display: Text",
    category: "output",
    description: "Text output display.",
    inputs: [{ id: "text", label: "Text Data", type: "text", required: true }],
    outputs: [],
    params: [],
    defaults: {},
    outputMode: "text",
    wrapperAvailable: false,
    rawCliAvailable: false,
    constraints: {},
    warnings: [],
  },
];

export function getDefaultPollSeconds(commandName: string): number {
  return commandName.includes("video") ? 1800 : 300;
}
